name: 'SCP'
description: 'SCP files to a remote destination'
author: 'kapoko'
inputs:
  host:
    description: 'ssh remote host'
    required: true
  username:
    description: 'ssh remote user'
    required: true
  password:
    description: 'ssh remote password'
  port:
    description: 'ssh remote port'
    default: 22
  private_key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  proxy_host:
    description: 'ssh proxy host'
  proxy_username:
    description: 'ssh proxy user'
  proxy_password:
    description: 'ssh proxy password'
  proxy_port:
    description: 'ssh proxy port'
    default: 22
  proxy_private_key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  command:
    description: 'optional command to be run before the scp action is run'
  command_after:
    description: 'optional command to be run after the scp action is run'
  source: 
    description: 'relative path of the local folder to be uploaded'
  target: 
    description: 'path on the remote host'
  include_dotfiles: 
    description: 'wether or not to include files starting with a dot'
    default: true
  dry_run:
    description: "connect to the host but don't actually upload files or execute commands"
    default: false
  preserve_hierarchy: 
    description: "keep folder structure of given source paths intact when copying to the remote "
    default: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'truck'
  color: 'green'
