name: Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci 
          npm run build

      - name: Run jest tests
        run: npm test
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PORT : ${{ secrets.PORT }}
          SECOND_HOST: ${{ secrets.SECOND_HOST }}
          SECOND_USERNAME: ${{ secrets.SECOND_USERNAME }}
          SECOND_PASSWORD: ${{ secrets.SECOND_PASSWORD }}
          SECOND_PRIVATE_KEY: ${{ secrets.SECOND_PRIVATE_KEY }}
          SECOND_PORT : ${{ secrets.SECOND_PORT }}

  integration-tests: 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create some test files
        run: |
          mkdir -p testFiles/anotherDir
          echo "Hello" >> testFiles/hello.txt
          echo "world" >> testFiles/anotherDir/world.txt

      - name: Test - Upload files with key
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          local: testFiles
          remote: .

      - name: Test - Upload files with password
        uses: ./
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          local: testFiles
          remote: .